version: '3'
services:
  db:
     build: ./mariadb
     restart : always
     container_name: mariadb
     environment:
           MYSQL_ROOT_PASSWORD: "123"
     ports:
           - "3300:3306"
     volumes:
        - "~/docker-compose/mariadb/initdb.d:/docker-entrypoint-initdb.d"
        - "~/docker-compose/mariadb/mariadb:/etc/mysql/conf.d/"   
  flask:
     build: ./flask
     container_name: flask
     ports:
           - "5000:5000"
     links:
           - 'db:mysq' 
                 
